package com.mycompany.uno;


import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author aemre
 */
public class ChoosingColor extends javax.swing.JFrame {

    private Card.Renk wildColor = null;
    Boolean permission = false;
    Window popUp;
    
    public ChoosingColor(){
        initComponents();
    }
    
    public ChoosingColor(Window pop){
        initComponents();
        popUp = pop;
    }
    
    public Card.Renk choseColor(Card card){
        if(card.getColor() == Card.Renk.Siyah){
            this.setBounds(100,150,600,700);
            this.setVisible(true);
            this.setResizable(false);    
        }
        return card.getColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setText("PICK THE COLOR");

        redButton.setBackground(new java.awt.Color(255, 204, 204));
        redButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        redButton.setForeground(new java.awt.Color(0, 0, 0));
        redButton.setText("Red");
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });

        blueButton.setBackground(new java.awt.Color(255, 204, 204));
        blueButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        blueButton.setForeground(new java.awt.Color(0, 0, 0));
        blueButton.setText("Blue");
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });

        greenButton.setBackground(new java.awt.Color(255, 204, 204));
        greenButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        greenButton.setForeground(new java.awt.Color(0, 0, 0));
        greenButton.setText("Green");
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });

        yellowButton.setBackground(new java.awt.Color(255, 204, 204));
        yellowButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        yellowButton.setForeground(new java.awt.Color(0, 0, 0));
        yellowButton.setText("Yellow");
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(yellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
        wildColor = Card.Renk.Sari;
        JLabel message = new JLabel("The Wild Card Color is Yellow! ");
        message.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null,message);
        permission = true;
        this.dispose();
        popUp.throwedColor  = Card.Renk.Sari;
        popUp.gamephase.setName(popUp.game.getCurrentPlayer());
        popUp.gamephase.setIconsofButtons();
        popUp.cardButtonOnTop.setIcon(new javax.swing.ImageIcon("C:\\Users\\aemre\\OneDrive\\Masaüstü\\images\\PNGs\\small\\" + popUp.game.cardOnTopImage()));
        popUp.game.setCardColor(Card.Renk.Sari);
        popUp.dispose();
    }//GEN-LAST:event_yellowButtonActionPerformed

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        wildColor = Card.Renk.Kirmizi;
        JLabel message = new JLabel("The Wild Card Color is Red! ");
        message.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null,message);
        permission = true;
        this.dispose();
        popUp.throwedColor  = Card.Renk.Kirmizi;
        popUp.gamephase.setName(popUp.game.getCurrentPlayer());
        popUp.gamephase.setIconsofButtons();
        
        popUp.cardButtonOnTop.setIcon(new javax.swing.ImageIcon("C:\\Users\\aemre\\OneDrive\\Masaüstü\\images\\PNGs\\small\\" + popUp.game.cardOnTopImage()));
        popUp.game.setCardColor(Card.Renk.Kirmizi);
        popUp.dispose();
    }//GEN-LAST:event_redButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        wildColor = Card.Renk.Mavi;
        JLabel message = new JLabel("The Wild Card Color is Blue! ");
        message.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null,message);
        permission = true;
        this.dispose();
        popUp.throwedColor  = Card.Renk.Mavi;
        popUp.gamephase.setName(popUp.game.getCurrentPlayer());
        popUp.gamephase.setIconsofButtons();
        
        popUp.cardButtonOnTop.setIcon(new javax.swing.ImageIcon("C:\\Users\\aemre\\OneDrive\\Masaüstü\\images\\PNGs\\small\\" + popUp.game.cardOnTopImage()));
        popUp.game.setCardColor(Card.Renk.Mavi);
        popUp.dispose();
    }//GEN-LAST:event_blueButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        wildColor = Card.Renk.Yesil;
        JLabel message = new JLabel("The Wild Card Color is Green! ");
        message.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null,message);
        permission = true;
        this.dispose();
        popUp.throwedColor  = Card.Renk.Yesil;
        popUp.gamephase.setName(popUp.game.getCurrentPlayer());
        popUp.gamephase.setIconsofButtons();
        popUp.cardButtonOnTop.setIcon(new javax.swing.ImageIcon("C:\\Users\\aemre\\OneDrive\\Masaüstü\\images\\PNGs\\small\\" + popUp.game.cardOnTopImage()));
        popUp.game.setCardColor(Card.Renk.Yesil);
        popUp.dispose();
    }//GEN-LAST:event_greenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoosingColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoosingColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoosingColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoosingColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoosingColor().setVisible(true);
            }          
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton redButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables

}
